services:
  postgres:
    image: postgres:16
    container_name: lionpay-postgres
    ports:
      - "9955:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lionpay-network
    restart: always

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: lionpay-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb - inMemory"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - lionpay-network
    restart: always

  auth-service:
    image: lionpay/auth-service:dev
    build:
      context: .
      dockerfile: lionpay-auth/Dockerfile
    container_name: auth-service
    ports:
      - "7755:8080"
      - "5005:5005" # For remote debugging
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      DYNAMODB_URL: ${DYNAMODB_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: lionpay-auth
      JWT_USER_AUDIENCE: lionpay-app
      JWT_ADMIN_AUDIENCE: lionpay-management
      SUPER_ADMIN_USERNAME: ${SUPER_ADMIN_USERNAME}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      OTEL_SERVICE_NAME: lionpay-auth
    depends_on:
      - dynamodb
    networks:
      - lionpay-network

  wallet-migrations:
    image: lionpay/wallet-migrations:dev
    build:
      context: .
      dockerfile: lionpay-wallet-migrations/Dockerfile
    container_name: wallet-migrations
    environment:
      ConnectionStrings__walletdb: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - lionpay-network

  wallet-service:
    image: lionpay/wallet-service:dev
    build:
      context: .
      dockerfile: lionpay-wallet/Dockerfile
    container_name: wallet-service
    ports:
      - "8855:8080"
    environment:
      ConnectionStrings__walletdb: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      JWT__Secret: ${JWT_SECRET}
      JWT__Issuer: lionpay-auth
      JWT__Audiences: lionpay-app,lionpay-management
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: lionpay-wallet
    depends_on:
      postgres:
        condition: service_started
      wallet-migrations:
        condition: service_completed_successfully
    networks:
      - lionpay-network

  app:
    image: lionpay/app:dev
    build:
      context: lionpay-app
      dockerfile: Dockerfile
    container_name: app-service
    environment:
      AUTH_SERVICE_URL: http://auth-service
      WALLET_SERVICE_URL: http://wallet-service
    ports:
      - "8866:80"
    depends_on:
      - auth-service
      - wallet-service
    networks:
      - lionpay-network

  management-service:
    image: lionpay/management-service:dev
    build:
      context: lionpay-management
      dockerfile: Dockerfile
    container_name: management-service
    environment:
      AUTH_SERVICE_URL: http://auth-service
      WALLET_SERVICE_URL: http://wallet-service
    ports:
      - "8877:80"
    depends_on:
      - auth-service
      - wallet-service
    networks:
      - lionpay-network

  alloy:
    image: grafana/alloy:latest
    container_name: lionpay-alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --stability.level=experimental --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./lgtm/alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - "13345:12345"
      - "14317:4317"
      - "14318:4318"
    depends_on:
      - loki
      - tempo
      - mimir
    networks:
      - lionpay-network

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./lgtm/loki/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - lionpay-network

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./lgtm/tempo/tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "4317"  # otlp grpc
    networks:
      - lionpay-network

  mimir:
    image: grafana/mimir:latest
    command: [ "-config.file=/etc/mimir.yaml" ]
    volumes:
      - ./lgtm/mimir/mimir-config.yaml:/etc/mimir.yaml
    ports:
      - "9009:9009"
    networks:
      - lionpay-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./lgtm/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    networks:
      - lionpay-network

networks:
  lionpay-network:


volumes:
  postgres-data:
  dynamodb-data:
