spring:
  application:
    name: lionpay-auth

aws:
  region: ap-northeast-2
  dynamodb:
    endpoint: http://localhost:8000
    access-key: dummy
    secret-key: dummy

jwt:
  secret: "b25lLXRpbWUtc2VjcmV0LWtleS1mb3Itand0LXNlY3VyaXR5LWV4YW1wbGU="
  access-token-expiration-minutes: 30
  refresh-token-expiration-days: 7

logging:
  level:
    root: INFO
    com.likelion: DEBUG