server:
  port: 8080
spring:
  application:
    name: lionpay-auth
aws:
  region: ${AWS_REGION:ap-northeast-2}
  dynamodb:
    endpoint: ${DYNAMODB_URL:}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    table-name: ${DYNAMODB_TABLE_NAME:lionpay-auth}

jwt:
  secret: ${JWT_SECRET:SGVsbG9Xb3JsZFRoaXNJc0FTZWNyZXRLZXlGb3JMb2NhbFRlc3Rpbmc=}
  issuer: ${JWT_ISSUER:lionpay-auth}
  user-audience: ${JWT_USER_AUDIENCE:lionpay-app}
  admin-audience: ${JWT_ADMIN_AUDIENCE:lionpay-management}
  access-token-expiration-minutes: 30
  refresh-token-expiration-days: 7
logging:
  level:
    root: INFO
    com.likelion: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /openapi
    groups.enabled: true
  swagger-ui:
    path: /swagger.html
  paths-to-match:
    - /api/**
    - /admin/**
super-admin:
  username: ${SUPER_ADMIN_USERNAME:admin}
  password: ${SUPER_ADMIN_PASSWORD:password}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
